# Generated by Django 2.1.2 on 2018-11-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pending_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('note', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='FavProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvp.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='comment',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvp.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_inventory_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_order_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_suppliers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_no',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('invoice_received', 'Invoice received'), ('paid_full', 'Paid (full)'), ('paid_partial', 'Paid (partial)'), ('disputed', 'Disputed'), ('due', 'due')], max_length=18),
        ),
        migrations.AddField(
            model_name='favproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Product'),
        ),
        migrations.AddField(
            model_name='favproducts',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Restaurant'),
        ),
        migrations.AddField(
            model_name='favproducts',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Supplier'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Restaurant'),
        ),
        migrations.AddField(
            model_name='associatedsupplier',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Restaurant'),
        ),
        migrations.AddField(
            model_name='associatedsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Supplier'),
        ),
    ]
