# Generated by Django 2.1.2 on 2019-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_order_checked_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Invoice received', 'Invoice received'), ('Paid (full)', 'Paid (full)'), ('Paid (partial)', 'Paid (partial)'), ('Disputed', 'Disputed'), ('due', 'due')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Checked-In', 'Checked-In')], max_length=18),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Missing/Not Delivered', 'Missing/Not Delivered'), ('Received (Full)', 'Received (Full)'), ('Received (Partial)', 'Received (Partial)'), ('Returned', 'Returned'), ('New/Substitute', 'New/Substitute')], max_length=18),
        ),
    ]
