# Generated by Django 2.1.2 on 2018-12-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvp', '0002_auto_20181215_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favproducts',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='favproducts',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='associated_suppliers',
            field=models.ManyToManyField(through='mvp.AssociatedSupplier', to='mvp.Supplier'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fav_products',
            field=models.ManyToManyField(blank=True, null=True, to='mvp.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mvp.Restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mvp.Supplier'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mvp.Order'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mvp.Supplier'),
        ),
        migrations.DeleteModel(
            name='FavProducts',
        ),
    ]
