# Generated by Django 2.1.2 on 2018-12-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20181215_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
