# Generated by Django 2.1.2 on 2019-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_auto_20190623_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
