# Generated by Django 2.1.2 on 2018-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_order_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
