# Generated by Django 2.1.2 on 2019-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_auto_20191002_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_checked_in',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
