# Generated by Django 2.1.2 on 2019-12-13 16:47

from django.db import migrations, models
import django_extensions.db.fields

# Generated by Django 2.1.2 on 2019-12-13 16:21
from django.utils.text import slugify


def gen_slug(apps, schema_editor):
    Supplier = apps.get_model('mvp', 'Supplier')
    for row in Supplier.objects.all():
        row.slug = slugify(row.name)
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0007_auto_20191026_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True,
                                                            populate_from='name'),
        ),
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop)
    ]
