# Generated by Django 2.1.2 on 2018-12-15 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0007_auto_20181215_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
    ]
