# Generated by Django 2.1.2 on 2020-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_auto_20200211_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
