# Generated by Django 2.1.2 on 2018-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_auto_20181215_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('invoice_received', 'Invoice received'), ('paid_full', 'Paid (full)'), ('paid_partial', 'Paid (partial)'), ('disputed', 'Disputed'), ('due', 'due')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
