# Generated by Django 2.1.2 on 2020-02-25 09:20

from django.db import migrations, models


def copy_product_to_order_item_model(apps, schema_editor):
    order_item = apps.get_model('mvp', 'OrderItem')
    for row in order_item.objects.all():
        product = row.product
        row.description = product.description
        row.name = product.name
        row.price = product.price
        row.sku = product.sku
        row.unit = product.unit
        row.save(update_fields=['description', 'name', 'price', 'sku', 'unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0010_order_whatsapp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(copy_product_to_order_item_model, reverse_code=migrations.RunPython.noop)
    ]
