# Generated by Django 2.1.2 on 2018-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0011_auto_20181215_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
