# Generated by Django 2.1.2 on 2018-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_auto_20181218_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_received',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('missing', 'Missing/Not Delivered'), ('received_full', 'Received (Full)'), ('received_partial', 'Received (Partial)'), ('returned', 'Returned'), ('new', 'New/Substitute')], max_length=18),
        ),
    ]
