# Generated by Django 2.1.2 on 2018-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0013_auto_20181222_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty_received',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
