# Generated by Django 2.1.2 on 2018-12-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_auto_20181222_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvp.Supplier'),
            preserve_default=False,
        ),
    ]
