# Generated by Django 2.1.2 on 2018-12-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0017_auto_20181227_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='amount',
        ),
    ]
