# Generated by Django 2.1.2 on 2019-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0018_auto_20181227_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='note',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
