# Generated by Django 2.1.2 on 2019-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0019_auto_20190515_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
